# .strealit/secrets.toml

[tidb]
host="gateway01.eu-central-1.prod.aws.tidbcloud.com"
user="4AE2NmSwgmagf82.root"
password="DJKUhp7bIen7VX3K"
port=4000, database="test"
ssl-ca={"ca": "cacert.perm"}
database="streamlit"
